const KEY='fl-esports-data-v1';
const ADMIN_CODE='Stikeli';
const defaults={activeLeague:'1. Liga',leagues:{'1. Liga':{teams:[['FL Titans',10,8,2,0,26,11],['Ravens Esports',10,7,1,2,22,13],['Nova Gaming',10,6,2,2,20,14],['Phoenix',10,5,1,4,17,16],['Vortex',10,3,2,5,11,20],['Blue Wolves',10,1,2,7,5,24]],form:[['W','W','W','D','W'],['W','L','W','W','W'],['W','D','L','W','W'],['L','W','W','L','D'],['L','D','L','W','L'],['L','L','D','L','L']]},'2. Liga':{teams:[['Storm United',8,7,0,1,21,8],['Blackout',8,5,2,1,17,10],['Red Lions',8,4,1,3,13,12],['Galaxy',8,3,2,3,11,13],['Iron Five',8,2,1,5,7,17],['Echo',8,1,0,7,3,22]],form:[['W','W','W','W','W'],['W','D','W','L','W'],['L','W','W','D','L'],['D','L','W','L','W'],['L','W','L','L','D'],['L','L','L','L','L']]}}};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function calc(t){return {name:t[0],sp:t[1],w:t[2],d:t[3],l:t[4],gf:t[5],ga:t[6],pts:t[2]*3+t[3],diff:t[5]-t[6]}}
function sorted(league){return league.teams.map((t,i)=>({...calc(t),form:league.form[i]})).sort((a,b)=>b.pts-a.pts||b.diff-a.diff||b.gf-a.gf)}
function nav(active){return `<header class="top"><nav class="nav"><div class="brand">FL <b>ESPORTS</b></div><button class="${active==='home'?'active':''}" onclick="home()">Ligen</button><button class="${active==='matches'?'active':''}" onclick="matches()">Spiele</button><button class="${active==='admin'?'active':''} adminBtn" onclick="admin()">Admin</button></nav></header>`}
function table(league){const rows=sorted(league).map((t,i)=>`<tr><td class="rank">${i+1}</td><td class="team">${t.name}</td><td>${t.sp}</td><td>${t.w}</td><td>${t.d}</td><td>${t.l}</td><td>${t.gf}:${t.ga}</td><td>${t.diff>0?'+':''}${t.diff}</td><td><div class="form">${t.form.map(x=>`<span class="${x==='W'?'w':x==='D'?'d':'l'}">${x}</span>`).join('')}</div></td><td><strong>${t.pts}</strong></td></tr>`).join('');return `<div class="tableWrap"><table class="leagueTable"><thead><tr><th>#</th><th>Team</th><th>Sp</th><th>S</th><th>U</th><th>N</th><th>Tore</th><th>Diff</th><th>Form</th><th>Pkt</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function home(){const l=data.activeLeague, league=data.leagues[l], s=sorted(league), total=s.reduce((a,t)=>a+t.pts,0);document.getElementById('app').innerHTML=nav('home')+`<main class="wrap"><section class="hero"><div class="eyebrow">FL ESPORTS • OFFICIAL LEAGUE</div><h1>${l}</h1><p>Alle Tabellen, Ergebnisse und Teamformen auf einen Blick. Punkte, Tordifferenz und Form werden automatisch aus den Ligadaten berechnet.</p></section><div class="cards"><div class="card"><div class="num">${s.length}</div><small>Teams</small></div><div class="card"><div class="num">${s.reduce((a,t)=>a+t.sp,0)/2|0}</div><small>Spieltage</small></div><div class="card"><div class="num">${s[0]?.pts||0}</div><small>Spitzenreiter-Punkte</small></div><div class="card"><div class="num">${s[0]?.diff>0?'+':''}${s[0]?.diff||0}</div><small>Beste Tordifferenz</small></div></div><section class="panel"><div class="panelHead"><h2>Ligatabelle</h2><div class="tabs">${Object.keys(data.leagues).map(x=>`<button class="tab ${x===l?'active':''}" onclick="setLeague('${x}')">${x}</button>`).join('')}</div></div>${table(league)}</section><div class="matchGrid"><div class="match card"><div class="meta">NÄCHSTER SPIELTAG</div><div class="score"><span>${s[0]?.name}</span><strong>VS</strong><span>${s[3]?.name}</span></div></div><div class="match card"><div class="meta">TOP TEAM</div><div class="score"><span>${s[0]?.name}</span><strong>${s[0]?.pts}</strong></div></div><div class="match card"><div class="meta">FORM</div><div class="score"><span>${s[0]?.name}</span><strong>${s[0]?.form.join('')}</strong></div></div></div></main><footer class="footer">FL Esports © 2026 · Alle Daten werden über das Admin-System verwaltet.</footer>`}
function setLeague(x){data.activeLeague=x;save();home()}
function matches(){document.getElementById('app').innerHTML=nav('matches')+`<main class="wrap"><section class="hero"><div class="eyebrow">FL ESPORTS</div><h1>Spiele</h1><p>Spieltag-Übersicht und Ergebnisse. Ergebnisse können im Adminbereich gepflegt werden.</p></section><div class="matchGrid">${['FL Titans vs Ravens Esports','Nova Gaming vs Phoenix','Storm United vs Blackout','Red Lions vs Galaxy','Iron Five vs Echo','Vortex vs Blue Wolves'].map((m,i)=>`<div class="match card"><div class="meta">${i<3?'1. LIGA':'2. LIGA'} · SPIELTAG ${i+1}</div><div class="score"><span>${m.split(' vs ')[0]}</span><strong>–</strong><span>${m.split(' vs ')[1]}</span></div></div>`).join('')}</div></main>`}
function admin(){document.getElementById('app').innerHTML=nav('admin')+`<main class="wrap"><div id="adminContent" class="login panel"><h2>Admin-Zugang</h2><p class="muted">Gib den Admin-Code ein, um die komplette Website zu verwalten.</p><div class="field"><label>ADMIN-CODE</label><input id="code" type="password" placeholder="Code eingeben"></div><button class="primary" onclick="login()">Dashboard öffnen</button></div></main>`}
function login(){if(document.getElementById('code').value!==ADMIN_CODE){alert('Falscher Admin-Code.');return}renderDashboard()}
function renderDashboard(){document.getElementById('app').innerHTML=nav('admin')+`<main class="wrap"><section class="hero"><div class="eyebrow">ADMIN CONTROL</div><h1>Dashboard</h1><p>Verwalte Ligen, Teams, Punkte, Tore und Form. Änderungen werden lokal gespeichert und sofort auf der Website übernommen.</p></section><div class="adminGrid"><section class="panel adminBox"><h3>Team bearbeiten</h3><div class="field"><label>LIGA</label><select id="league">${Object.keys(data.leagues).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>TEAM</label><select id="team"></select></div><div class="row"><div class="field"><label>SPIELE</label><input id="sp" type="number"></div><div class="field"><label>SIEGE</label><input id="w" type="number"></div><div class="field"><label>UNENTSCHIEDEN</label><input id="d" type="number"></div><div class="field"><label>NIEDERLAGEN</label><input id="l" type="number"></div><div class="field"><label>TORE</label><input id="gf" type="number"></div><div class="field"><label>GEGENTORE</label><input id="ga" type="number"></div></div><div class="actions"><button class="primary" onclick="updateTeam()">Speichern</button><button class="primary" onclick="addTeam()">Team hinzufügen</button></div></section><section class="panel adminBox"><h3>Teamname & Form</h3><div class="field"><label>NEUER NAME</label><input id="newname"></div><div class="field"><label>FORM (5 ZEICHEN: W / D / L)</label><input id="form" maxlength="5" placeholder="WWDLW"></div><button class="primary" onclick="updateMeta()">Speichern</button><hr style="border-color:#22304a;margin:22px 0"><div class="notice"><b>Berechnung:</b> Punkte = Siege × 3 + Unentschieden. Differenz = Tore − Gegentore. Die Tabelle sortiert automatisch nach Punkte, Differenz und Toren.</div><div class="actions"><button class="primary danger" onclick="resetData()">Demo-Daten zurücksetzen</button></div></section></div></main>`;syncTeamOptions()}
function syncTeamOptions(){const l=document.getElementById('league');const t=document.getElementById('team');if(!l||!t)return;const lg=data.leagues[l.value];t.innerHTML=lg.teams.map((x,i)=>`<option value="${i}">${x[0]}</option>`).join('');loadTeam();l.onchange=syncTeamOptions;t.onchange=loadTeam}
function loadTeam(){const i=+document.getElementById('team').value, l=document.getElementById('league').value, t=data.leagues[l].teams[i],f=data.leagues[l].form[i];['sp','w','d','l','gf','ga'].forEach((id,j)=>document.getElementById(id).value=t[j+1]);document.getElementById('newname').value=t[0];document.getElementById('form').value=f.join('')}
function updateTeam(){const l=document.getElementById('league').value,i=+document.getElementById('team').value,t=data.leagues[l].teams[i];['sp','w','d','l','gf','ga'].forEach((id,j)=>t[j+1]=+document.getElementById(id).value);save();renderDashboard();alert('Teamdaten gespeichert.')}
function updateMeta(){const l=document.getElementById('league').value,i=+document.getElementById('team').value;data.leagues[l].teams[i][0]=document.getElementById('newname').value.trim()||'Team';let f=document.getElementById('form').value.toUpperCase().replace(/[^WDL]/g,'').slice(0,5).split('');while(f.length<5)f.push('D');data.leagues[l].form[i]=f;save();renderDashboard();alert('Name und Form gespeichert.')}
function addTeam(){const l=document.getElementById('league').value;data.leagues[l].teams.push(['Neues Team',0,0,0,0,0,0]);data.leagues[l].form.push(['D','D','D','D','D']);save();renderDashboard()}
function resetData(){if(confirm('Alle Demo-Daten wiederherstellen?')){data=structuredClone(defaults);save();renderDashboard()}}
home();
