const KEY='fl-esports-v2', ADMIN_CODE='Stikeli';
const defaultData={
  settings:{brand:'FL ESPORTS',season:'Saison 2026',subtitle:'Competitive League • Official Platform',accent:'#6d5dfc',pointsWin:3,pointsDraw:1,pointsLoss:0},
  activeLeague:'1. Liga',
  leagues:{
    '1. Liga':{teams:[
      {id:'t1',name:'FL Titans',short:'FLT',color:'#6d5dfc',logo:'⚡'},{id:'t2',name:'Ravens Esports',short:'RAV',color:'#f04d6d',logo:'🦅'},{id:'t3',name:'Nova Gaming',short:'NVA',color:'#00c2ff',logo:'✦'},{id:'t4',name:'Phoenix',short:'PHX',color:'#ff9b3d',logo:'🔥'},{id:'t5',name:'Vortex',short:'VTX',color:'#34d399',logo:'◈'},{id:'t6',name:'Blue Wolves',short:'BLW',color:'#4f82ff',logo:'🐺'}
    ],matches:[
      ['m1','2026-09-05','18:00','t1','t2',3,1,'played'],['m2','2026-09-05','19:30','t3','t4',2,2,'played'],['m3','2026-09-06','18:00','t5','t6',1,0,'played'],
      ['m4','2026-09-12','18:00','t1','t3',null,null,'scheduled'],['m5','2026-09-12','19:30','t2','t5',null,null,'scheduled'],['m6','2026-09-13','18:00','t4','t6',null,null,'scheduled'],
      ['m7','2026-09-19','18:00','t6','t1',null,null,'scheduled'],['m8','2026-09-19','19:30','t3','t2',null,null,'scheduled'],['m9','2026-09-20','18:00','t5','t4',null,null,'scheduled']
    ]},
    '2. Liga':{teams:[
      {id:'t7',name:'Storm United',short:'STU',color:'#3b82f6',logo:'⚡'},{id:'t8',name:'Blackout',short:'BLK',color:'#a855f7',logo:'◉'},{id:'t9',name:'Red Lions',short:'RDL',color:'#ef4444',logo:'🦁'},{id:'t10',name:'Galaxy',short:'GAL',color:'#22d3ee',logo:'✹'},{id:'t11',name:'Iron Five',short:'IR5',color:'#64748b',logo:'◆'},{id:'t12',name:'Echo',short:'ECO',color:'#eab308',logo:'◌'}
    ],matches:[
      ['m10','2026-09-05','18:00','t7','t8',2,0,'played'],['m11','2026-09-05','19:30','t9','t10',1,1,'played'],['m12','2026-09-06','18:00','t11','t12',0,2,'played'],
      ['m13','2026-09-12','18:00','t8','t9',null,null,'scheduled'],['m14','2026-09-12','19:30','t10','t11',null,null,'scheduled'],['m15','2026-09-13','18:00','t12','t7',null,null,'scheduled'],
      ['m16','2026-09-19','18:00','t9','t7',null,null,'scheduled'],['m17','2026-09-19','19:30','t8','t10',null,null,'scheduled'],['m18','2026-09-20','18:00','t11','t12',null,null,'scheduled']
    ]}
  },
  news:[
    {id:'n1',title:'Neue Saison gestartet',text:'Willkommen zur neuen FL Esports Saison. Tabellen und Spielplan sind live.',date:'2026-08-25',tag:'ANNOUNCEMENT'},
    {id:'n2',title:'Das Rennen um Platz 1',text:'Die ersten Ergebnisse versprechen eine enge Saison in der 1. Liga.',date:'2026-08-26',tag:'NEWS'}
  ]
};
let data=load();let isAdmin=false;document.documentElement.style.setProperty('--accent',data.settings.accent||'#6d5dfc');
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function team(id){for(const l of Object.values(data.leagues)){const t=l.teams.find(x=>x.id===id);if(t)return t}return {id,name:'Unknown',short:'?',color:'#64748b',logo:'?'}}
function stats(league){const map=Object.fromEntries(league.teams.map(t=>[t.id,{team:t,sp:0,w:0,d:0,l:0,gf:0,ga:0}]));league.matches.filter(m=>m[7]==='played').forEach(m=>{const h=map[m[3]],a=map[m[4]],hg=Number(m[5]),ag=Number(m[6]);if(!h||!a)return;h.sp++;a.sp++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++}else if(hg<ag){a.w++;h.l++}else{h.d++;a.d++}});return Object.values(map).map(s=>({...s,pts:s.w*Number(data.settings.pointsWin??3)+s.d*Number(data.settings.pointsDraw??1)+s.l*Number(data.settings.pointsLoss??0),diff:s.gf-s.ga,form:formFor(league,s.team.id)})).sort((a,b)=>b.pts-a.pts||b.diff-a.diff||b.gf-a.gf||a.team.name.localeCompare(b.team.name))}
function formFor(league,id){return league.matches.filter(m=>m[7]==='played'&&(m[3]===id||m[4]===id)).slice(-5).map(m=>m[3]===id?(m[5]>m[6]?'W':m[5]<m[6]?'L':'D'):(m[6]>m[5]?'W':m[6]<m[5]?'L':'D')).reverse()}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function shell(title,active,body){document.title=`${title} | ${data.settings.brand}`;document.getElementById('app').innerHTML=`<div class="site"><header><div class="nav"><button class="brand" onclick="go('home')"><span class="brandMark">FL</span><span>${esc(data.settings.brand.replace('FL ',''))}</span></button><div class="links">${[['home','Home'],['leagues','Ligen'],['matches','Spiele'],['teams','Teams'],['stats','Stats']].map(([r,n])=>`<button class="${active===r?'on':''}" onclick="go('${r}')">${n}</button>`).join('')}</div><div class="navRight"><span class="season">${esc(data.settings.season)}</span><button class="adminLink" onclick="go('admin')">⚙ Admin</button></div></div></header>${body}<footer><b>${esc(data.settings.brand)}</b><span>${esc(data.settings.subtitle)}</span><span>© 2026 • League Management Platform</span></footer></div>`}
function hero(kicker,title,text){return `<section class="hero"><div class="kicker">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(text)}</p></section>`}
function leagueTabs(){return `<div class="leagueTabs">${Object.keys(data.leagues).map(l=>`<button class="${data.activeLeague===l?'active':''}" onclick="setLeague('${l}')">${l}</button>`).join('')}</div>`}
function tableHtml(league){return `<div class="tableCard"><div class="tableScroll"><table><thead><tr><th>#</th><th>Team</th><th>Sp</th><th>S</th><th>U</th><th>N</th><th>Tore</th><th>Diff</th><th>Form</th><th>Pkt</th></tr></thead><tbody>${stats(league).map((s,i)=>`<tr onclick="teamPage('${s.team.id}')"><td class="rank ${i<3?'top':''}">${i+1}</td><td><div class="teamCell"><span class="teamLogo" style="--c:${s.team.color}">${esc(s.team.logo)}</span><b>${esc(s.team.name)}</b><small>${esc(s.team.short)}</small></div></td><td>${s.sp}</td><td>${s.w}</td><td>${s.d}</td><td>${s.l}</td><td>${s.gf}:${s.ga}</td><td class="${s.diff>=0?'positive':'negative'}">${s.diff>0?'+':''}${s.diff}</td><td><div class="form">${s.form.length?s.form.map(x=>`<i class="${x.toLowerCase()}">${x}</i>`).join(''):'<span class="muted">–</span>'}</div></td><td><strong>${s.pts}</strong></td></tr>`).join('')}</tbody></table></div></div>`}
function home(){const l=data.leagues[data.activeLeague],all=Object.values(data.leagues),allMatches=all.flatMap(x=>x.matches),played=allMatches.filter(m=>m[7]==='played').length,upcoming=allMatches.filter(m=>m[7]!=='played').sort((a,b)=>(a[1]+a[2]).localeCompare(b[1]+b[2])).slice(0,3);shell('Home','home',`<main>${hero(data.settings.subtitle,data.settings.season,'Alle Ergebnisse, Tabellen, Spieltage und Teamstatistiken der FL Esports League – zentral verwaltet und sofort aktualisiert.')}<div class="statsGrid"><div class="metric"><span>Teams</span><b>${all.reduce((a,x)=>a+x.teams.length,0)}</b><small>2 Ligen</small></div><div class="metric"><span>Spiele gespielt</span><b>${played}</b><small>live berechnet</small></div><div class="metric"><span>Offene Spiele</span><b>${allMatches.length-played}</b><small>im Spielplan</small></div><div class="metric"><span>Aktive Liga</span><b class="smallMetric">${esc(data.activeLeague)}</b><small>Tabellenansicht</small></div></div><div class="homeGrid"><section><div class="sectionHead"><div><span class="eyebrow">CURRENT STANDINGS</span><h2>${esc(data.activeLeague)}</h2></div>${leagueTabs()}</div>${tableHtml(l)}</section><aside class="sideStack"><div class="panel"><div class="panelTitle">Nächste Spiele</div>${upcoming.map(matchMini).join('')||'<div class="empty">Keine offenen Spiele</div>'}</div><div class="panel"><div class="panelTitle">News</div>${data.news.slice(0,3).map(n=>`<article class="newsItem"><span>${esc(n.tag)} • ${fmtDate(n.date)}</span><b>${esc(n.title)}</b><p>${esc(n.text)}</p></article>`).join('')}</div></aside></div></main>`)}
function matchMini(m){const h=team(m[3]),a=team(m[4]);return `<button class="matchMini" onclick="matchPage('${m[0]}')"><span>${fmtDate(m[1])} · ${m[2]}</span><div><b>${esc(h.name)}</b><strong>${m[7]==='played'?m[5]:'–'}</strong><em>:</em><strong>${m[7]==='played'?m[6]:'–'}</strong><b>${esc(a.name)}</b></div><small>${esc(findLeagueForMatch(m[0]))}</small></button>`}
function findLeagueForMatch(id){return Object.keys(data.leagues).find(l=>data.leagues[l].matches.some(m=>m[0]===id))||''}
function leagues(){shell('Ligen','leagues',`<main>${hero('LEAGUES','Ligaübersicht','Zwei Wettbewerbe, eine Plattform. Öffne eine Liga für Tabelle, Spielplan und alle Ergebnisse.')}<div class="leagueCards">${Object.entries(data.leagues).map(([name,l])=>{const s=stats(l);return `<button class="leagueHero" onclick="setLeague('${name}');go('leagues')"><div class="leagueBadge">${name==='1. Liga'?'1':'2'}</div><div><span>${name}</span><h3>${esc(s[0]?.team.name||'–')}</h3><p>Tabellenführer • ${s[0]?.pts||0} Punkte</p></div><strong>→</strong></button>`}).join('')}</div><section class="panel leaguePanel">${leagueTabs()}${tableHtml(data.leagues[data.activeLeague])}</section></main>`)}
function matches(){const league=data.leagues[data.activeLeague],byDay={};league.matches.forEach(m=>(byDay[m[1]]??=[]).push(m));shell('Spiele','matches',`<main>${hero(data.activeLeague+' • MATCH CENTER','Spielplan & Ergebnisse','Alle Begegnungen nach Datum. Admins können Ergebnisse eintragen und die Tabelle aktualisiert sich automatisch.')}${leagueTabs()}<div class="days">${Object.entries(byDay).map(([d,ms])=>`<section class="day"><div class="dayHead"><b>${fmtDate(d)}</b><span>Spieltag</span></div>${ms.map(matchRow).join('')}</section>`).join('')}</div></main>`)}
function matchRow(m){const h=team(m[3]),a=team(m[4]);return `<button class="matchRow" onclick="matchPage('${m[0]}')"><div class="date">${m[2]}</div><div class="side"><span class="teamLogo" style="--c:${h.color}">${esc(h.logo)}</span><b>${esc(h.name)}</b></div><div class="scoreBox">${m[7]==='played'?`<strong>${m[5]} : ${m[6]}</strong><small>FINAL</small>`:`<strong>– : –</strong><small>GEPLANT</small>`}</div><div class="side right"><b>${esc(a.name)}</b><span class="teamLogo" style="--c:${a.color}">${esc(a.logo)}</span></div></button>`}
function teams(){shell('Teams','teams',`<main>${hero('ROSTERS','Teams','Alle Teams der FL Esports Ligen mit Bilanz, Form und direktem Zugriff auf die Teamansicht.')}<div class="teamGrid">${Object.entries(data.leagues).flatMap(([lname,l])=>l.teams.map(t=>{const s=stats(l).find(x=>x.team.id===t.id);return `<button class="teamCard" onclick="teamPage('${t.id}')"><span class="teamLogo big" style="--c:${t.color}">${esc(t.logo)}</span><div><small>${esc(lname)}</small><h3>${esc(t.name)}</h3><p>${s.pts} Pkt · ${s.w}-${s.d}-${s.l}</p><div class="form">${s.form.map(x=>`<i class="${x.toLowerCase()}">${x}</i>`).join('')}</div></div><strong>›</strong></button>`}))}</div></main>`)}
function statsPage(){const leaders=Object.entries(data.leagues).map(([l,x])=>[l,stats(x)]);shell('Statistiken','stats',`<main>${hero('STATISTICS','Liga-Statistiken','Leistungsdaten über beide Ligen, automatisch aus den gespeicherten Ergebnissen berechnet.')}<div class="statPanels">${leaders.map(([l,s])=>`<section class="panel"><div class="panelTitle">${l}</div><div class="leaderRows">${s.slice(0,6).map((x,i)=>`<div class="leaderRow"><span>${i+1}</span><span class="teamCell"><span class="teamLogo" style="--c:${x.team.color}">${esc(x.team.logo)}</span><b>${esc(x.team.name)}</b></span><b>${x.pts} Pkt</b><span class="positive">${x.diff>0?'+':''}${x.diff} Diff</span></div>`).join('')}</div></section>`).join('')}</div></main>`)}
function teamPage(id){const t=team(id),leagueName=findLeagueForTeam(id),l=data.leagues[leagueName],s=stats(l).find(x=>x.team.id===id),games=l.matches.filter(m=>m[3]===id||m[4]===id).sort((a,b)=>b[1].localeCompare(a[1]));shell(t.name,'teams',`<main>${hero(leagueName,t.name,`Teamseite • ${s.pts} Punkte • ${s.w} Siege • ${s.d} Unentschieden • ${s.l} Niederlagen`)}<div class="teamHero"><span class="teamLogo xl" style="--c:${t.color}">${esc(t.logo)}</span><div><small>${esc(t.short)}</small><h2>${esc(t.name)}</h2><p>${esc(leagueName)}</p></div><div class="teamRecord">${['sp','w','d','l','gf','ga','diff','pts'].map(k=>`<div><span>${labels[k]}</span><b>${s[k]}</b></div>`).join('')}</div></div><section class="panel"><div class="panelTitle">Letzte Spiele</div>${games.map(matchRow).join('')||'<div class="empty">Noch keine Spiele</div>'}</section></main>`)}
const labels={sp:'Spiele',w:'Siege',d:'U',l:'N',gf:'Tore',ga:'Gegentore',diff:'Diff',pts:'Punkte'};
function findLeagueForTeam(id){return Object.keys(data.leagues).find(l=>data.leagues[l].teams.some(t=>t.id===id))||'1. Liga'}
function matchPage(id){let found;for(const [ln,l] of Object.entries(data.leagues)){const m=l.matches.find(x=>x[0]===id);if(m){found=[ln,l,m];break}}if(!found)return matches();const [ln,l,m]=found,h=team(m[3]),a=team(m[4]);shell('Spiel','matches',`<main>${hero(ln,'Match Center',`${fmtDate(m[1])} • ${m[2]} • ${m[7]==='played'?'Endergebnis':'Geplant'}`)}<div class="matchDetail"><div class="detailTeam"><span class="teamLogo xl" style="--c:${h.color}">${esc(h.logo)}</span><h2>${esc(h.name)}</h2></div><div class="bigScore">${m[7]==='played'?`${m[5]}<span>:</span>${m[6]}`:'VS'}</div><div class="detailTeam"><span class="teamLogo xl" style="--c:${a.color}">${esc(a.logo)}</span><h2>${esc(a.name)}</h2></div></div><section class="panel"><div class="panelTitle">Match-Information</div><div class="infoGrid"><span>Status<b>${m[7]==='played'?'Final':'Geplant'}</b></span><span>Liga<b>${ln}</b></span><span>Datum<b>${fmtDate(m[1])}</b></span><span>Uhrzeit<b>${m[2]}</b></span></div></section></main>`)}
function setLeague(x){data.activeLeague=x;save();if(location.hash.includes('matches'))matches();else if(location.hash.includes('leagues'))leagues();else home()}
function go(route){location.hash=route;renderRoute()}
function renderRoute(){const r=(location.hash||'#home').slice(1).split('/');switch(r[0]){case'leagues':leagues();break;case'matches':matches();break;case'teams':r[1]?teamPage(r[1]):teams();break;case'stats':statsPage();break;case'admin':admin();break;default:home()}}
function admin(){if(!isAdmin){shell('Admin','admin',`<main><div class="loginCard panel"><div class="kicker">CONTROL CENTER</div><h1>Admin Login</h1><p>Nur mit dem Admin-Code zugänglich.</p><input id="adminCode" class="input" type="password" placeholder="Code"><button class="primary full" onclick="login()">Dashboard öffnen</button><small class="muted">Demo-Code ist im Projekt konfiguriert.</small></div></main>`);return}adminDash()}
function login(){if(document.getElementById('adminCode').value===ADMIN_CODE){isAdmin=true;adminDash()}else alert('Falscher Admin-Code.')}
function adminDash(){const l=data.leagues[data.activeLeague];shell('Admin','admin',`<main>${hero('CONTROL CENTER','Admin Dashboard','Verwalte Website, Ligen, Teams, Ergebnisse, News und Saison direkt über dieses CMS.')}<div class="adminTabs"><button class="active" onclick="adminDash()">Übersicht</button><button onclick="adminTeams()">Teams</button><button onclick="adminMatches()">Ergebnisse</button><button onclick="adminNews()">News</button><button onclick="adminSettings()">Einstellungen</button></div><div class="adminGrid"><section class="panel adminPanel"><div class="panelTitle">Schnellaktionen</div><div class="quick"><button class="primary" onclick="adminMatches()">+ Ergebnis eintragen</button><button class="secondary" onclick="adminTeams()">+ Team verwalten</button><button class="secondary" onclick="adminNews()">+ News</button></div></section><section class="panel adminPanel"><div class="panelTitle">Live Status</div><div class="infoGrid"><span>1. Liga<b>${stats(data.leagues['1. Liga'])[0]?.team.name||'–'}</b></span><span>2. Liga<b>${stats(data.leagues['2. Liga'])[0]?.team.name||'–'}</b></span><span>Spiele<b>${Object.values(data.leagues).reduce((a,x)=>a+x.matches.length,0)}</b></span><span>News<b>${data.news.length}</b></span></div></section></div><section class="panel adminPanel"><div class="panelTitle">Tabellen-Vorschau · ${esc(data.activeLeague)}</div>${tableHtml(l)}</section></main>`)}
function adminTeams(){const html=Object.entries(data.leagues).map(([ln,l])=>`<section class="panel adminPanel"><div class="panelTitle">${ln}<button class="smallBtn" onclick="newTeam('${ln}')">+ Team</button></div>${l.teams.map(t=>`<div class="adminItem"><span class="teamLogo" style="--c:${t.color}">${esc(t.logo)}</span><div><b>${esc(t.name)}</b><small>${esc(t.short)}</small></div><button onclick="editTeam('${ln}','${t.id}')">Bearbeiten</button><button class="dangerBtn" onclick="removeTeam('${ln}','${t.id}')">Löschen</button></div>`).join('')}</section>`).join('');shell('Admin • Teams','admin',`<main>${hero('CMS','Teamverwaltung','Namen, Kürzel, Farben und Logos der Teams anpassen.')}<div class="adminGrid">${html}</div><button class="secondary" onclick="adminDash()">← Dashboard</button></main>`)}
function editTeam(ln,id){const t=data.leagues[ln].teams.find(x=>x.id===id);document.getElementById('app').innerHTML+=modal('Team bearbeiten',`<div class="formGrid"><label>Name<input id="eName" value="${esc(t.name)}"></label><label>Kürzel<input id="eShort" value="${esc(t.short)}"></label><label>Logo/Emoji<input id="eLogo" value="${esc(t.logo)}"></label><label>Farbe<input id="eColor" type="color" value="${t.color}"></label></div><div class="modalActions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveTeam('${ln}','${id}')">Speichern</button></div>`)}
function saveTeam(ln,id){const t=data.leagues[ln].teams.find(x=>x.id===id);t.name=document.getElementById('eName').value.trim()||'Team';t.short=document.getElementById('eShort').value.trim()||'NEW';t.logo=document.getElementById('eLogo').value.trim()||'★';t.color=document.getElementById('eColor').value;save();closeModal();adminTeams()}
function newTeam(ln){document.getElementById('app').innerHTML+=modal('Neues Team',`<div class="formGrid"><label>Name<input id="nName"></label><label>Kürzel<input id="nShort"></label><label>Logo/Emoji<input id="nLogo" value="★"></label><label>Farbe<input id="nColor" type="color" value="#6d5dfc"></label></div><div class="modalActions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="createTeam('${ln}')">Erstellen</button></div>`)}
function createTeam(ln){const t={id:'team_'+Date.now(),name:document.getElementById('nName').value.trim()||'Neues Team',short:document.getElementById('nShort').value.trim()||'NEW',logo:document.getElementById('nLogo').value.trim()||'★',color:document.getElementById('nColor').value};data.leagues[ln].teams.push(t);save();closeModal();adminTeams()}
function removeTeam(ln,id){if(confirm('Team und zugehörige Spiele wirklich löschen?')){const l=data.leagues[ln];l.teams=l.teams.filter(t=>t.id!==id);l.matches=l.matches.filter(m=>m[3]!==id&&m[4]!==id);save();adminTeams()}}
function adminMatches(){const options=Object.entries(data.leagues).flatMap(([ln,l])=>l.teams.map(t=>`<option value="${t.id}">${ln} — ${esc(t.name)}</option>`)).join('');const rows=Object.entries(data.leagues).map(([ln,l])=>l.matches.map(m=>{const h=team(m[3]),a=team(m[4]);return `<div class="adminItem"><div><b>${fmtDate(m[1])} ${m[2]}</b><small>${esc(h.name)} vs ${esc(a.name)}</small></div><span class="status ${m[7]}">${m[7]==='played'?m[5]+' : '+m[6]:'offen'}</span><button onclick="editMatch('${ln}','${m[0]}')">Bearbeiten</button><button class="dangerBtn" onclick="deleteMatch('${ln}','${m[0]}')">Löschen</button></div>`}).join('')).join('');shell('Admin • Matches','admin',`<main>${hero('RESULTS CMS','Ergebnisse verwalten','Spieltermine und Resultate pflegen. Gespielte Ergebnisse berechnen automatisch Punkte, Torbilanz und Form.')}<section class="panel adminPanel"><div class="panelTitle">Neues Spiel <select id="newLeague" class="selectSmall">${Object.keys(data.leagues).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="formGrid"><label>Datum<input id="nmDate" type="date" value="2026-09-27"></label><label>Uhrzeit<input id="nmTime" type="time" value="18:00"></label><label>Heimteam<select id="nmHome">${options}</select></label><label>Auswärtsteam<select id="nmAway">${options}</select></label><label>Status<select id="nmStatus"><option value="scheduled">Geplant</option><option value="played">Gespielt</option></select></label><label>Heimtore<input id="nmHG" type="number" min="0" value="0"></label><label>Auswärtstore<input id="nmAG" type="number" min="0" value="0"></label></div><button class="primary" onclick="createMatch()">Spiel anlegen</button></section><section class="panel adminPanel"><div class="panelTitle">Bestehende Spiele</div>${rows}</section></main>`)}
function createMatch(){const ln=document.getElementById('newLeague').value,l=data.leagues[ln],m=['m_'+Date.now(),document.getElementById('nmDate').value,document.getElementById('nmTime').value,document.getElementById('nmHome').value,document.getElementById('nmAway').value,Number(document.getElementById('nmHG').value),Number(document.getElementById('nmAG').value),document.getElementById('nmStatus').value];if(m[3]===m[4])return alert('Heim- und Auswärtsteam müssen unterschiedlich sein.');if(m[7]==='scheduled'){m[5]=null;m[6]=null}l.matches.push(m);save();adminMatches()}
function editMatch(ln,id){const m=data.leagues[ln].matches.find(x=>x[0]===id);document.getElementById('app').innerHTML+=modal('Spiel bearbeiten',`<div class="formGrid"><label>Datum<input id="mDate" type="date" value="${m[1]}"></label><label>Uhrzeit<input id="mTime" type="time" value="${m[2]}"></label><label>Status<select id="mStatus"><option value="scheduled" ${m[7]==='scheduled'?'selected':''}>Geplant</option><option value="played" ${m[7]==='played'?'selected':''}>Gespielt</option></select></label><label>Heimtore<input id="mHG" type="number" min="0" value="${m[5]??0}"></label><label>Auswärtstore<input id="mAG" type="number" min="0" value="${m[6]??0}"></label></div><div class="modalActions"><button class="secondary" onclick="closeModal()">Abbrechen</button><button class="primary" onclick="saveMatch('${ln}','${id}')">Speichern</button></div>`)}
function saveMatch(ln,id){const m=data.leagues[ln].matches.find(x=>x[0]===id);m[1]=document.getElementById('mDate').value;m[2]=document.getElementById('mTime').value;m[7]=document.getElementById('mStatus').value;m[5]=m[7]==='played'?Number(document.getElementById('mHG').value):null;m[6]=m[7]==='played'?Number(document.getElementById('mAG').value):null;save();closeModal();adminMatches()}
function deleteMatch(ln,id){if(confirm('Spiel löschen?')){data.leagues[ln].matches=data.leagues[ln].matches.filter(m=>m[0]!==id);save();closeModal();adminMatches()}}
function adminNews(){shell('Admin • News','admin',`<main>${hero('CONTENT CMS','News & Meldungen','Beiträge der Startseite direkt aus dem Adminbereich pflegen.')}<section class="panel adminPanel"><div class="panelTitle">Neue Meldung</div><div class="formGrid"><label>Titel<input id="nnTitle"></label><label>Tag<input id="nnTag" value="NEWS"></label><label class="wide">Text<textarea id="nnText" rows="4"></textarea></label></div><button class="primary" onclick="createNews()">Veröffentlichen</button></section><section class="panel adminPanel"><div class="panelTitle">Bestehende Meldungen</div>${data.news.map(n=>`<div class="adminItem"><div><b>${esc(n.title)}</b><small>${esc(n.tag)} • ${fmtDate(n.date)}</small></div><button onclick="editNews('${n.id}')">Bearbeiten</button><button class="dangerBtn" onclick="deleteNews('${n.id}')">Löschen</button></div>`).join('')}</section></main>`)}
function createNews(){data.news.unshift({id:'n_'+Date.now(),title:document.getElementById('nnTitle').value||'Neue Meldung',text:document.getElementById('nnText').value,tag:(document.getElementById('nnTag').value||'NEWS').toUpperCase(),date:new Date().toISOString().slice(0,10)});save();adminNews()}
function editNews(id){const n=data.news.find(x=>x.id===id);document.getElementById('app').innerHTML+=modal('Meldung bearbeiten',`<div class="formGrid"><label>Titel<input id="neTitle" value="${esc(n.title)}"></label><label>Tag<input id="neTag" value="${esc(n.tag)}"></label><label class="wide">Text<textarea id="neText" rows="5">${esc(n.text)}</textarea></label></div><div class="modalActions"><button class="primary" onclick="saveNews('${id}')">Speichern</button></div>`)}
function saveNews(id){const n=data.news.find(x=>x.id===id);n.title=document.getElementById('neTitle').value;n.tag=document.getElementById('neTag').value.toUpperCase();n.text=document.getElementById('neText').value;save();closeModal();adminNews()}
function deleteNews(id){data.news=data.news.filter(n=>n.id!==id);save();adminNews()}
function adminSettings(){shell('Admin • Einstellungen','admin',`<main>${hero('SITE CMS','Website Einstellungen','Branding, Saison und Punktesystem zentral verwalten.')}<section class="panel adminPanel"><div class="formGrid"><label>Brand<input id="setBrand" value="${esc(data.settings.brand)}"></label><label>Saison<input id="setSeason" value="${esc(data.settings.season)}"></label><label class="wide">Untertitel<input id="setSubtitle" value="${esc(data.settings.subtitle)}"></label><label>Akzentfarbe<input id="setAccent" type="color" value="${data.settings.accent}"></label><label>Sieg-Punkte<input id="setPW" type="number" min="0" value="${data.settings.pointsWin}"></label><label>Remis-Punkte<input id="setPD" type="number" min="0" value="${data.settings.pointsDraw}"></label><label>Niederlagen-Punkte<input id="setPL" type="number" min="0" value="${data.settings.pointsLoss}"></label></div><button class="primary" onclick="saveSettings()">Einstellungen speichern</button></section><section class="panel adminPanel"><div class="panelTitle">System</div><div class="quick"><button class="secondary" onclick="exportData()">Daten exportieren</button><button class="secondary" onclick="importData()">Daten importieren</button><button class="dangerBtn" onclick="factoryReset()">Alles zurücksetzen</button></div></section></main>`)}
function saveSettings(){data.settings.brand=document.getElementById('setBrand').value;data.settings.season=document.getElementById('setSeason').value;data.settings.subtitle=document.getElementById('setSubtitle').value;data.settings.accent=document.getElementById('setAccent').value;data.settings.pointsWin=Number(document.getElementById('setPW').value);data.settings.pointsDraw=Number(document.getElementById('setPD').value);data.settings.pointsLoss=Number(document.getElementById('setPL').value);document.documentElement.style.setProperty('--accent',data.settings.accent);save();adminSettings()}
function exportData(){navigator.clipboard?.writeText(JSON.stringify(data));alert('Daten wurden in die Zwischenablage kopiert.')}
function importData(){const raw=prompt('JSON-Daten einfügen:');if(!raw)return;try{data=JSON.parse(raw);save();location.reload()}catch{alert('Ungültige JSON-Daten.')}}
function factoryReset(){if(confirm('Alle Änderungen und Daten wirklich zurücksetzen?')){data=structuredClone(defaultData);save();location.reload()}}
function modal(title,body){return `<div class="modalBack" id="modal"><div class="modal"><button class="close" onclick="closeModal()">×</button><h2>${title}</h2>${body}</div></div>`}
function closeModal(){document.getElementById('modal')?.remove()}
window.addEventListener('hashchange',renderRoute);renderRoute();
