const STORAGE_KEY='dayflow-v3';
const todayKey=()=>dateKey(new Date());
let selectedDate=todayKey(), calendarCursor=new Date(), focusSeconds=1500, focusRunning=false, focusInterval=null, deferredInstall=null;
const quotes=['Ein guter Tag beginnt nicht mit mehr Aufgaben, sondern mit den richtigen.','Du musst nicht alles schaffen. Du musst das Richtige schaffen.','Kleine Schritte zählen. Besonders die, die du wirklich machst.','Fokus ist eine Entscheidung, keine Stimmung.','Deine Zeit ist dein eigentliches Budget.','Ein geplanter Pausenmoment ist kein verlorener Moment.'];
const fallback={version:3,profile:null,tasks:[],habits:[{id:uid(),name:'Wasser trinken',emoji:'💧',history:[]},{id:uid(),name:'Kurz bewegen',emoji:'🚶',history:[]}],notes:[],checkins:{},theme:'light',generatedDates:[],weather:null,notifications:false};
const state=loadState();
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function loadState(){try{return {...fallback,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(fallback)}}
function save(render=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); if(render)renderAll()}
function dateKey(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10)}
function parseKey(k){return new Date(k+'T12:00:00')}
function fmtDate(d){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d)}
function fmtShort(d){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}).format(d)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function mins(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}
function timeStr(n){n=((n%1440)+1440)%1440;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function getTasks(date=selectedDate){return state.tasks.filter(t=>t.date===date).sort((a,b)=>mins(a.start)-mins(b.start))}
function renderAll(){applyTheme();updateHeader();renderTimeline();renderTopThree();renderHabits();renderNotes();renderStats();renderProfile();renderCalendar();updateGoal();syncHero()}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark')}
function updateHeader(){const h=new Date().getHours();document.getElementById('greeting').textContent=h<12?'Guten Morgen':h<18?'Guten Tag':'Guten Abend';document.getElementById('currentDate').textContent=fmtDate(parseKey(selectedDate));document.getElementById('datePill').textContent=selectedDate===todayKey()?'Heute':fmtShort(parseKey(selectedDate));document.getElementById('quoteText').textContent=quotes[parseKey(selectedDate).getDay()%quotes.length];document.getElementById('coachLine').textContent=state.profile?.name?`Für ${state.profile.name}`:'DayFlow Reminder'}
function updateClock(){document.getElementById('liveClock').textContent=new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function syncHero(){const p=state.profile;if(!p){document.getElementById('heroText').textContent='Fülle dein Profil aus – DayFlow erstellt daraus direkt einen passenden Tagesablauf und speichert ihn automatisch.';return} const name=p.name?`, ${p.name}`:'';document.getElementById('heroText').textContent=`Dein persönlicher Plan ist gespeichert${name}. Er verbindet Fokus, Bewegung, Essen, Pausen und Erholung.`;document.getElementById('daySummary').textContent=`${getTasks(selectedDate).length} Zeitblöcke · automatisch aus deinem Profil`}
function taskCard(t){return `<div class="task-card ${t.done?'done':''}" draggable="true" data-id="${t.id}"><div class="task-main"><button class="task-check" onclick="toggleTask('${t.id}')" aria-label="erledigt"></button><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="tag">${esc(t.start)}–${esc(t.end)}</span><span class="tag">${esc(t.category||'Allgemein')}</span>${t.priority==='high'?'<span class="tag priority-high">Wichtig</span>':''}${t.auto?'<span class="tag">Auto</span>':''}</div></div></div><div class="task-actions"><button class="tiny-btn" onclick="moveTaskEarlier('${t.id}')" title="früher">↑</button><button class="tiny-btn" onclick="moveTaskLater('${t.id}')" title="später">↓</button><button class="tiny-btn" onclick="deleteTask('${t.id}')">×</button></div></div>`}
function renderTimeline(){const root=document.getElementById('timeline');const tasks=getTasks();if(!tasks.length){root.innerHTML=`<div class="empty-state">🌿<h3>Dein Tag ist leer</h3><p>Erstelle einen automatischen Plan oder füge Aufgaben hinzu.</p><button class="primary-btn" onclick="generatePlan('${selectedDate}')">✨ Plan erstellen</button></div>`;return}root.innerHTML=tasks.map(taskCard).join('')}
function renderTopThree(){const top=getTasks().filter(t=>t.top).slice(0,3);document.getElementById('topThree').innerHTML=top.length?top.map((t,i)=>`<div class="top-item"><b>${i+1}</b><span>${esc(t.title)}</span></div>`).join(''):'<div class="subtle">Noch keine Top-3. Markiere wichtige Aufgaben beim Hinzufügen.</div>'}
function habitStreak(h){let c=0;for(let i=0;i<60;i++){const d=new Date();d.setDate(d.getDate()-i);if(h.history.includes(dateKey(d)))c++;else break}return c}
function renderHabits(){const el=document.getElementById('habitsGrid');let weekdays=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);weekdays.push(dateKey(d))}el.innerHTML=state.habits.map(h=>`<div class="habit-card"><div class="habit-top"><span class="habit-emoji">${esc(h.emoji)}</span><button class="tiny-btn" onclick="deleteHabit('${h.id}')">×</button></div><div class="habit-name">${esc(h.name)}</div><div class="habit-streak">${habitStreak(h)} Tage Serie</div><div class="habit-days">${weekdays.map(k=>`<button class="habit-day ${h.history.includes(k)?'checked':''}" onclick="toggleHabit('${h.id}','${k}')">${parseKey(k).getDate()}</button>`).join('')}</div></div>`).join('')||'<div class="empty-state">Noch keine Gewohnheiten.</div>'}
function renderNotes(){const el=document.getElementById('notesGrid');el.innerHTML=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="note-card"><div class="note-toolbar"><span class="eyebrow">${esc(n.type||'Notiz')}</span><button class="tiny-btn" onclick="deleteNote('${n.id}')">×</button></div><h4>${esc(n.title)}</h4><p>${esc(n.body||'')}</p><div class="note-meta">${esc(n.createdAt)}</div></div>`).join(''):'<div class="empty-state">Deine Notizen erscheinen hier.</div>'}
function renderProfile(){const p=state.profile||{};['Name','Age','Weight','Height','Sleep','Wake','Bed','Activity','Goal','WorkStart','WorkEnd'].forEach(k=>{const id='profile'+k,el=document.getElementById(id);if(el)el.value=p[k.toLowerCase()]??''});document.getElementById('profileHello').textContent=p.name?`Hallo, ${esc(p.name)}!`:'Dein Profil';const bmi=p.age>=18&&p.weight&&p.height?(p.weight/((p.height/100)**2)).toFixed(1):null;const summary=[['Alter',p.age?`${p.age} Jahre`:'—'],['Gewicht',p.weight?`${p.weight} kg`:'—'],['Schlaf',p.sleep?`${p.sleep} h`:'—'],['Aktivität',activityLabel(p.activity)],['Ziel',goalLabel(p.goal)],['BMI',bmi?`${bmi} · nur grobe Orientierung`:'nicht verwendet']];document.getElementById('profileSummary').innerHTML=summary.map(([a,b])=>`<div class="profile-chip"><span>${a}</span><strong>${b}</strong></div>`).join('');document.getElementById('suggestionGrid').innerHTML=makeSuggestions(p).map(s=>`<article class="suggestion"><div class="suggestion-emoji">${s.e}</div><h4>${esc(s.t)}</h4><p>${esc(s.d)}</p></article>`).join('')}
function activityLabel(v){return {low:'Ruhig',medium:'Normal aktiv',high:'Sehr aktiv'}[v]||'—'}function goalLabel(v){return {balance:'Balance',fitness:'Fitness',focus:'Fokus',recovery:'Erholung',school:'Schule/Lernen'}[v]||'—'}
function makeSuggestions(p){if(!p)return[];const a=[];if(p.goal==='focus')a.push({e:'🎯',t:'Fokusblöcke',d:'Plane 25–50 Minuten konzentriertes Arbeiten und 5–10 Minuten Pause.'});else if(p.goal==='fitness'||p.activity==='high')a.push({e:'🏃',t:'Bewegung',d:'Ein Trainings- oder Spaziergangsblock ist bereits im Plan eingeplant.'});else a.push({e:'🚶',t:'Alltagsbewegung',d:'Mehrmals am Tag kurz aufstehen, gehen oder strecken.'});if(Number(p.sleep)<7)a.push({e:'🌙',t:'Schlaf priorisieren',d:'Abends früher runterfahren und möglichst konstant schlafen.'});else a.push({e:'🛌',t:'Schlafrhythmus',d:'Ähnliche Schlaf- und Aufstehzeiten helfen bei einem stabilen Tagesrhythmus.'});a.push({e:'🥗',t:'Mahlzeiten planen',d:'Frühstück, Mittag und Abendessen sind als feste Tagesblöcke vorgesehen.'});a.push({e:'💧',t:'Regelmäßig trinken',d:'Wasser über den Tag verteilt bereitstellen und bei Pausen daran denken.'});a.push({e:'🧠',t:'Kopf frei bekommen',d:'Kurzer Brain Dump oder eine Notizsession ist als Werkzeug direkt verfügbar.'});if(Number(p.age)<18)a.push({e:'🧡',t:'Wohlbefinden statt Gewicht',d:'Bei Jugendlichen stehen Schlaf, Bewegung, regelmäßiges Essen und Wohlbefinden im Mittelpunkt.'});else a.push({e:'⚖️',t:'Gesamten Alltag betrachten',d:'Gewicht allein ist kein verlässliches Maß für Gesundheit; DayFlow nutzt es daher nicht für Abnehm- oder Kalorienziele.'});return a}
function saveProfileData(obj,goPlan=true){state.profile={name:obj.name||'',age:String(obj.age||''),weight:String(obj.weight||''),height:String(obj.height||''),sleep:String(obj.sleep||8),wake:obj.wake||'07:00',bed:obj.bed||'23:00',activity:obj.activity||'medium',goal:obj.goal||'balance',workstart:obj.workstart||'09:00',workend:obj.workend||'16:00'};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));generatePlan(todayKey(),true);renderAll();if(goPlan){closeModal('onboardingModal');switchView('today');selectedDate=todayKey();renderAll();toast('Profil gespeichert – dein Plan ist fertig ✨')}}
function generatePlan(date=todayKey(),force=false){if(!state.profile)return;const existing=getTasks(date);if(existing.length&&!force&&!state.generatedDates.includes(date))return; if(force)state.tasks=state.tasks.filter(t=>!(t.date===date&&t.auto));if(!force&&state.generatedDates.includes(date))return;const p=state.profile,w=mins(p.wake),bed=mins(p.bed),start=Math.max(w+60,mins(p.workstart)-30),end=Math.max(start+60,mins(p.workend));const tasks=[];const add=(title,s,dur,cat,priority='normal',top=false)=>tasks.push({id:uid(),date,title,start:timeStr(s),end:timeStr(s+dur),category:cat,priority,top,done:false,auto:true});
add('Aufstehen & ruhig starten',w,30,'Gesundheit','normal',false);add('Frühstück',w+35,25,'Essen','normal',false);add(p.goal==='school'?'Lern-/Arbeitsblock 1':'Fokusblock 1',start,60,p.goal==='school'?'Lernen':'Produktivität','high',true);add('Pause & kurz bewegen',start+65,15,'Pause');
const second=start+85;add(p.goal==='school'?'Lern-/Arbeitsblock 2':'Fokusblock 2',second,60,p.goal==='school'?'Lernen':'Produktivität','high',true);add('Mittagessen',second+70,35,'Essen');
if(p.activity==='high'||p.goal==='fitness')add('Bewegung / Training',second+115,50,'Gesundheit','high',true);else add('Spaziergang & Bewegung',second+115,25,'Gesundheit','normal');
const workFinish=Math.min(end,second+175);if(workFinish>second+145)add('Fokusblock 3 / Aufgaben',second+145,Math.min(60,workFinish-(second+145)),'Produktivität','normal');add('Freie Zeit / Interessen',Math.min(workFinish+15,bed-190),40,'Privat');add('Abendessen',Math.min(workFinish+60,bed-150),30,'Essen');add('Abend runterfahren',Math.max(bed-60,workFinish+100),30,'Pause');
const unique=[];for(const t of tasks){if(t.start===t.end)continue; if(!unique.some(x=>x.start===t.start&&x.title===t.title))unique.push(t)}state.tasks.push(...unique);if(!state.habits.find(h=>h.name==='Abendroutine'))state.habits.push({id:uid(),name:'Abendroutine',emoji:'🌙',history:[]});if(!state.generatedDates.includes(date))state.generatedDates.push(date);save(false);}
function addTask(e){e.preventDefault();state.tasks.push({id:uid(),date:selectedDate,title:taskTitle.value.trim(),start:taskStart.value,end:taskEnd.value,category:taskCategory.value,priority:taskPriority.value,top:taskTop.checked,done:false,auto:false});save();closeModal('taskModal');e.target.reset();toast('Aufgabe gespeichert')}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save();toast(t.done?'Erledigt ✅':'Wieder offen')}}function deleteTask(id){state.tasks=state.tasks.filter(t=>t.id!==id);save();toast('Aufgabe entfernt')}
function moveTaskEarlier(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.start=timeStr(mins(t.start)-15);t.end=timeStr(mins(t.end)-15);save()}function moveTaskLater(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.start=timeStr(mins(t.start)+15);t.end=timeStr(mins(t.end)+15);save()}
function addHabit(e){e.preventDefault();state.habits.push({id:uid(),name:habitName.value.trim(),emoji:habitEmoji.value||'✨',history:[]});save();closeModal('habitModal');e.target.reset();toast('Gewohnheit gespeichert')}
function toggleHabit(id,k){const h=state.habits.find(x=>x.id===id);if(!h)return;h.history=h.history.includes(k)?h.history.filter(x=>x!==k):[...h.history,k];save()}function deleteHabit(id){state.habits=state.habits.filter(h=>h.id!==id);save();toast('Gewohnheit gelöscht')}
function addNote(e){e.preventDefault();state.notes.push({id:uid(),type:'Notiz',title:noteTitle.value.trim(),body:noteBody.value,createdAt:new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date())});save();closeModal('noteModal');e.target.reset();toast('Notiz gespeichert')}function deleteNote(id){state.notes=state.notes.filter(n=>n.id!==id);save();toast('Notiz gelöscht')}
function createTool(type){const map={meal:['Essensplan','🍽 Frühstück – Mittag – Abendessen','Plan'],shopping:['Einkaufsliste','- ','Liste'],brain:['Brain Dump','Alles aufschreiben, ohne zu sortieren.','Notiz'],review:['Wochenreview','Was lief gut?\nWas war schwierig?\nWas ändere ich nächste Woche?','Review'],gratitude:['Dankbarkeit','Heute bin ich dankbar für:\n1.\n2.\n3.','Reflexion'],project:['Projekt-Milestone','Nächster konkreter Schritt: ','Projekt']};const [title,body,typeName]=map[type];state.notes.push({id:uid(),type:typeName,title,body,createdAt:new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date())});save();toast(`${title} erstellt`)}
function renderStats(){const today=getTasks(todayKey()),done=today.filter(t=>t.done).length,total=state.tasks.length,allDone=state.tasks.filter(t=>t.done).length,rate=total?Math.round(allDone/total*100):0,habitCount=state.habits.length;const streak=Math.max(0,...state.habits.map(h=>habitStreak(h)));const avgMood=Object.values(state.checkins).filter(x=>x.mood).reduce((a,x)=>a+x.mood,0)/(Object.values(state.checkins).filter(x=>x.mood).length||1);document.getElementById('statsGrid').innerHTML=[['Heute',`${done}/${today.length}`],['Gesamt erledigt',allDone],['Erfolgsquote',`${rate}%`],['Gewohnheiten',habitCount],['Beste Serie',`${streak} Tage`],['Ø Stimmung',`${avgMood.toFixed(1)}/5`]].map(v=>`<div class="stat-card"><span class="eyebrow">${v[0]}</span><div class="stat-value">${v[1]}</div><div class="stat-label">DayFlow Überblick</div></div>`).join('');const bars=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);const k=dateKey(d);bars.push({d,val:state.tasks.filter(t=>t.date===k&&t.done).length})}const max=Math.max(...bars.map(b=>b.val),1);document.getElementById('barChart').innerHTML=bars.map(b=>`<div class="bar-col"><div class="bar" style="height:${Math.max(8,b.val/max*165)}px"></div><span>${new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(b.d).slice(0,2)}</span></div>`).join('');document.getElementById('moodHistory').innerHTML=Object.entries(state.checkins).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,10).map(([k,v])=>`<div class="mood-row"><b>${fmtShort(parseKey(k))}</b><span>${['','😴','😕','🙂','😄','🤩'][v.mood]||'—'}</span><small>${esc(v.text||'')}</small></div>`).join('')||'<div class="subtle">Noch keine Check-ins.</div>'}
function updateGoal(){const a=getTasks(),d=a.filter(t=>t.done).length,p=a.length?Math.round(d/a.length*100):0;document.getElementById('goalDone').textContent=d;document.getElementById('goalTotal').textContent=a.length;document.getElementById('goalPercent').textContent=p+'%';document.getElementById('goalRing').style.background=`conic-gradient(#8a6dff ${p*3.6}deg,#2b3547 ${p*3.6}deg)`}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));document.getElementById('view-'+v).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('pageTitle').textContent={today:'Dein Tagesplan',calendar:'Kalender',habits:'Gewohnheiten',notes:'Notizen',stats:'Statistik',profile:'Profil'}[v]||'DayFlow';if(v==='calendar')renderCalendar()}
function changeDay(d){const x=parseKey(selectedDate);x.setDate(x.getDate()+d);selectedDate=dateKey(x);if(state.profile&&!state.generatedDates.includes(selectedDate))generatePlan(selectedDate,false);renderAll()}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();document.getElementById('monthLabel').textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(calendarCursor);const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();let start=(first.getDay()+6)%7,html='';for(let i=0;i<start;i++)html+='<div class="cal-cell muted"></div>';for(let d=1;d<=days;d++){const k=dateKey(new Date(y,m,d)),tasks=getTasks(k),pct=tasks.length?Math.round(tasks.filter(t=>t.done).length/tasks.length*100):0;html+=`<button class="cal-cell ${k===selectedDate?'selected':''} ${k===todayKey()?'today':''}" onclick="pickCalendar('${k}')"><b>${d}</b><span>${tasks.length} Blöcke</span><i style="width:${pct}%"></i></button>`}document.getElementById('calendarGrid').innerHTML=html;document.getElementById('calendarDayTitle').textContent=fmtDate(parseKey(selectedDate));const tasks=getTasks();document.getElementById('calendarDayTasks').innerHTML=tasks.length?tasks.map(t=>`<div class="calendar-task"><span>${t.start}</span><strong>${esc(t.title)}</strong><small>${t.done?'Erledigt':'Offen'}</small></div>`).join(''):'<div class="subtle">Keine Aufgaben.</div>'}
function pickCalendar(k){selectedDate=k;if(state.profile&&!state.generatedDates.includes(k))generatePlan(k,false);calendarCursor=new Date(parseKey(k));renderAll()}
function startOnboarding(){document.getElementById('onboardingModal').classList.remove('hidden')}
function openModal(id){document.getElementById(id).classList.remove('hidden')}function closeModal(id){document.getElementById(id).classList.add('hidden')}
function toast(m){const x=document.getElementById('toast');x.textContent=m;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2300)}
function resetFocus(){focusRunning=false;clearInterval(focusInterval);focusSeconds=1500;updateFocusDisplay();focusStart.textContent='Start'}function updateFocusDisplay(){focusTimer.textContent=`${String(Math.floor(focusSeconds/60)).padStart(2,'0')}:${String(focusSeconds%60).padStart(2,'0')}`}function toggleFocus(){if(focusRunning){focusRunning=false;clearInterval(focusInterval);focusStart.textContent='Weiter'}else{focusRunning=true;focusStart.textContent='Pause';focusInterval=setInterval(()=>{focusSeconds--;updateFocusDisplay();if(focusSeconds<=0){resetFocus();toast('Fokus-Session beendet 🎉')}},1000)}}
async function shareDay(){const text=`${state.profile?.name||'Mein'} DayFlow-Tag\n`+getTasks().map(t=>`${t.start} ${t.title}${t.done?' ✓':''}`).join('\n');if(navigator.share){try{await navigator.share({title:'Mein DayFlow-Plan',text})}catch{}}else{await navigator.clipboard?.writeText(text);toast('Tagesplan kopiert')}}
function checkin(){openModal('checkinModal')}
function saveCheckinFn(){const mood=document.querySelector('[data-mood].selected')?.dataset.mood;if(!mood){toast('Wähle zuerst deine Stimmung');return}state.checkins[todayKey()]={mood:Number(mood),text:checkinText.value.trim()};save();closeModal('checkinModal');toast('Check-in gespeichert 💚')}
async function loadWeather(){const box=document.getElementById('weatherBox');box.innerHTML='<div class="subtle">Wetter wird geladen …</div>';if(!navigator.geolocation){box.innerHTML='<div class="subtle">Standort ist im Browser nicht verfügbar.</div>';return}navigator.geolocation.getCurrentPosition(async pos=>{try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`;const data=await fetch(url).then(r=>r.json());state.weather=data.current;save(false);const w=data.current;box.innerHTML=`<div class="weather-main"><b>${Math.round(w.temperature_2m)}°C</b><span>${weatherText(w.weather_code)}</span></div><div class="weather-meta">Wind ${Math.round(w.wind_speed_10m)} km/h</div>`}catch{box.innerHTML='<div class="subtle">Wetter konnte nicht geladen werden.</div>'}},()=>box.innerHTML='<div class="subtle">Standortzugriff abgelehnt – Wetter nicht geladen.</div>')}
function weatherText(code){if(code===0)return'Klar';if(code<=3)return'Bewölkt';if(code<=67)return'Regen';if(code<=77)return'Schnee';if(code<=99)return'Gewitter';return'Wetter'}
function requestNotifications(){if(!('Notification'in window)){toast('Dieser Browser unterstützt keine Benachrichtigungen');return}Notification.requestPermission().then(p=>{state.notifications=p==='granted';save(false);toast(p==='granted'?'Erinnerungen aktiviert 🔔':'Keine Berechtigung')})}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dayflow-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exportiert')}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{if(file.name.toLowerCase().endsWith('.ics')){importICS(reader.result);return}Object.assign(state,JSON.parse(reader.result));save();toast('Backup importiert')}catch{toast('Import fehlgeschlagen')}};reader.readAsText(file)}
function importICS(text){const events=[...text.matchAll(/BEGIN:VEVENT([\s\S]*?)END:VEVENT/g)].map(m=>m[1]);let count=0;for(const e of events){const sm=e.match(/DTSTART[^:]*:(\d{8})T?(\d{4})?/),nm=e.match(/SUMMARY:(.*)/);if(!sm||!nm)continue;const k=`${sm[1].slice(0,4)}-${sm[1].slice(4,6)}-${sm[1].slice(6,8)}`;state.tasks.push({id:uid(),date:k,title:nm[1].trim(),start:sm[2]?sm[2].slice(0,2)+':'+sm[2].slice(2):'09:00',end:sm[2]?timeStr(mins(sm[2].slice(0,2)+':'+sm[2].slice(2))+60):'10:00',category:'Kalender',priority:'normal',top:false,done:false,auto:false});count++}save();toast(`${count} Kalendertermine importiert`)}
function saveProfileForm(e){e.preventDefault();saveProfileData({name:profileName.value,age:profileAge.value,weight:profileWeight.value,height:profileHeight.value,sleep:profileSleep.value,wake:profileWake.value,bed:profileBed.value,activity:profileActivity.value,goal:profileGoal.value,workstart:profileWorkStart.value,workend:profileWorkEnd.value},true)}
function submitOnboarding(e){e.preventDefault();saveProfileData({name:onName.value,age:onAge.value,weight:onWeight.value,height:onHeight.value,sleep:onSleep.value,wake:onWake.value,bed:onBed.value,activity:onActivity.value,goal:onGoal.value,workstart:onWorkStart.value,workend:onWorkEnd.value},true)}

document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)switchView(nav.dataset.view);if(e.target.matches('[data-close]'))closeModal(e.target.dataset.close);if(e.target.id==='addTaskBtn')openModal('taskModal');if(e.target.id==='addHabitBtn')openModal('habitModal');if(e.target.id==='addNoteBtn')openModal('noteModal');if(e.target.id==='focusBtn')openModal('focusModal');if(e.target.id==='focusStart')toggleFocus();if(e.target.id==='focusReset')resetFocus();if(e.target.id==='prevDay')changeDay(-1);if(e.target.id==='nextDay')changeDay(1);if(e.target.id==='prevMonth'){calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()}if(e.target.id==='nextMonth'){calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()}if(e.target.id==='jumpToday'){selectedDate=todayKey();calendarCursor=new Date();renderAll()}if(e.target.id==='themeBtn'){state.theme=state.theme==='dark'?'light':'dark';save()}if(e.target.id==='exportBtn')exportData();if(e.target.id==='notifyBtn')requestNotifications();if(e.target.id==='shareBtn')shareDay();if(e.target.id==='checkinBtn')checkin();if(e.target.id==='saveCheckin')saveCheckinFn();if(e.target.id==='weatherBtn')loadWeather();if(e.target.id==='regenerateBtn'){generatePlan(todayKey(),true);selectedDate=todayKey();renderAll();toast('Tagesplan neu erstellt ✨')}const preset=e.target.closest('[data-min]');if(preset){focusSeconds=Number(preset.dataset.min)*60;document.querySelectorAll('.timer-presets button').forEach(b=>b.classList.remove('selected'));preset.classList.add('selected');updateFocusDisplay()}const tool=e.target.closest('[data-tool]');if(tool)createTool(tool.dataset.tool);const mood=e.target.closest('[data-mood]');if(mood){document.querySelectorAll('[data-mood]').forEach(b=>b.classList.remove('selected'));mood.classList.add('selected')}});
document.getElementById('profileForm').addEventListener('submit',saveProfileForm);document.getElementById('onboardingForm').addEventListener('submit',submitOnboarding);document.getElementById('taskForm').addEventListener('submit',addTask);document.getElementById('habitForm').addEventListener('submit',addHabit);document.getElementById('noteForm').addEventListener('submit',addNote);document.getElementById('importInput').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0])});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;installBtn.hidden=false});installBtn.addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;installBtn.hidden=true}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
updateClock();setInterval(updateClock,1000);updateFocusDisplay();renderAll();if(!state.profile)setTimeout(startOnboarding,180);else if(!state.generatedDates.includes(todayKey())){generatePlan(todayKey(),false);renderAll()}
window.toggleTask=toggleTask;window.deleteTask=deleteTask;window.toggleHabit=toggleHabit;window.deleteHabit=deleteHabit;window.deleteNote=deleteNote;window.openModal=openModal;window.closeModal=closeModal;window.moveTaskEarlier=moveTaskEarlier;window.moveTaskLater=moveTaskLater;window.generatePlan=generatePlan;window.pickCalendar=pickCalendar;
